# Generated by Django 6.1.1 on 2026-09-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PredictionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("locality", models.CharField(db_index=True, max_length=120)),
                ("total_sqft", models.FloatField()),
                ("bhk", models.PositiveSmallIntegerField()),
                ("bathrooms", models.PositiveSmallIntegerField()),
                (
                    "furnishing",
                    models.CharField(
                        choices=[
                            ("unfurnished", "Unfurnished"),
                            ("semi_furnished", "Semi-Furnished"),
                            ("fully_furnished", "Fully-Furnished"),
                        ],
                        max_length=20,
                    ),
                ),
                ("property_age", models.FloatField(default=0)),
                ("parking", models.BooleanField(default=False)),
                ("clubhouse", models.BooleanField(default=False)),
                ("metro_distance_km", models.FloatField(blank=True, null=True)),
                (
                    "predicted_price",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "price_per_sqft",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("range_low", models.DecimalField(decimal_places=2, max_digits=14)),
                ("range_high", models.DecimalField(decimal_places=2, max_digits=14)),
                ("model_used", models.CharField(default="xgboost", max_length=30)),
                (
                    "report",
                    models.FileField(blank=True, null=True, upload_to="reports/"),
                ),
                (
                    "emailed_to",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Prediction log",
                "verbose_name_plural": "Prediction logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
